# --- .github/workflows/run-script.yml ---
name: Run R script every hour at :35

on:
  schedule:
    - cron: "35 * * * *"   # elk uur op :35 (UTC)
  workflow_dispatch:

permissions:
  contents: write  # nodig om terug te committen

jobs:
  run-r:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Amsterdam
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Run script
        run: Rscript script.R

      - name: Commit CSV to repo
        uses: EndBug/add-and-commit@v9
        with:
          add: "data/*.csv"
          message: "Hourly export [skip ci]"
