# .github/workflows/run-script.yml
name: Run R script every hour at :35

on:
  schedule:
    - cron: "35 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-r:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Amsterdam
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::httr
            any::jsonlite
            any::dplyr
            any::purrr
            any::tidyr
      - name: Run script
        run: Rscript script.R
      - name: Commit data to repo
        uses: EndBug/add-and-commit@v9
        with:
          add: "data/*"
          message: "Hourly export + Deventer incremental [skip ci]"
