name: Run R script every hour at :35

on:
  schedule:
    - cron: "35 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-r:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Amsterdam
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      # installeer de benodigde packages
      - name: Install R packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::httr
            any::jsonlite
            any::dplyr
            any::purrr
            any::tidyr

      - name: Run script
        run: Rscript script.R

      - name: Commit CSV to repo
        uses: EndBug/add-and-commit@v9
        with:
          add: "data/*.csv"
          message: "Hourly export [skip ci]"
